require "json"
require "yaml"

require "./rosetta/version"
require "./rosetta/ext/fiber"
require "./rosetta/lucky/allowed_in_tags"
require "./rosetta/lucky/integration"
require "./rosetta/aliases"
require "./rosetta/config"
require "./rosetta/configuration"
require "./rosetta/backend"
require "./rosetta/interpolation"
require "./rosetta/localization"
require "./rosetta/localizable"
require "./rosetta/translation"
require "./rosetta/translatable"
